Repository Automattic/Automattic-Tracks-Android, pull requests merged in 2024-08, with the labels that each got.

#232 Expose more performance apis
  crashlogging/build.gradle
  crashlogging/src/main/java/com/automattic/android/tracks/crashlogging/performance/PerformanceMetricsTag.kt
  crashlogging/src/main/java/com/automattic/android/tracks/crashlogging/performance/PerformanceTransactionRepository.kt
  crashlogging/src/main/java/com/automattic/android/tracks/crashlogging/performance/SpanId.kt
  sampletracksapp/src/main/java/com/example/sampletracksapp/MainActivity.kt
Labels: enhancement

#235 [Dependency Analysis] Remove Unused Dependencies
  .buildkite/pipeline.yml
  .gitignore
  AutomatticTracks/build.gradle
  benchmark/build.gradle.kts
  benchmark/gradle.properties
  benchmark/src/main/AndroidManifest.xml
  build.gradle
  crashlogging/build.gradle
  sampletracksapp/build.gradle
  settings.gradle
Labels: Tooling, Core

#238 Introduce file-based persistence for Experimentation module
  experimentation/src/main/java/com/automattic/android/experimentation/local/FileBasedCache.kt
  experimentation/src/main/java/com/automattic/android/experimentation/remote/AssignmentsDtoMapper.kt
  experimentation/src/test/java/com/automattic/android/experimentation/local/FileBasedCacheTest.kt
Labels: enhancement

#239 Experimentation: replace FluxC with internal components
  build.gradle
  experimentation/build.gradle
  experimentation/src/main/java/com/automattic/android/experimentation/ExPlat.kt
  experimentation/src/main/java/com/automattic/android/experimentation/ExperimentLogger.kt
  experimentation/src/main/java/com/automattic/android/experimentation/domain/Assignments.kt
  experimentation/src/main/java/com/automattic/android/experimentation/domain/AssignmentsValidator.kt
  experimentation/src/main/java/com/automattic/android/experimentation/domain/Clock.kt
  experimentation/src/main/java/com/automattic/android/experimentation/local/FileBasedCache.kt
  experimentation/src/main/java/com/automattic/android/experimentation/remote/AssignmentsDtoMapper.kt
  experimentation/src/main/java/com/automattic/android/experimentation/remote/ExperimentRestClient.kt
  experimentation/src/main/java/com/automattic/android/experimentation/repository/AssignmentsRepository.kt
  experimentation/src/test/java/com/automattic/android/experimentation/ExPlatTest.kt
  experimentation/src/test/java/com/automattic/android/experimentation/local/FileBasedCacheTest.kt
  experimentation/src/test/java/com/automattic/android/experimentation/remote/AssignmentsDtoMapperTest.kt
  experimentation/src/test/java/com/automattic/android/experimentation/remote/ExperimentRestClientTest.kt
Labels: enhancement, [PR] Not Ready for Merge

#240 Support passing `anon_id` to ExPlat
  experimentation/src/main/java/com/automattic/android/experimentation/ExPlat.kt
  experimentation/src/main/java/com/automattic/android/experimentation/remote/UrlBuilder.kt
  experimentation/src/test/java/com/automattic/android/experimentation/local/FileBasedCacheTest.kt
  experimentation/src/test/java/com/automattic/android/experimentation/remote/ExperimentRestClientTest.kt
  experimentation/src/test/java/com/automattic/android/experimentation/remote/MockWebServerUrlBuilder.kt
Labels: enhancement

#242 Improve threading and test suite
  experimentation/build.gradle
  experimentation/src/main/java/com/automattic/android/experimentation/ExPlat.kt
  experimentation/src/main/java/com/automattic/android/experimentation/local/FileBasedCache.kt
  experimentation/src/main/java/com/automattic/android/experimentation/remote/ExperimentRestClient.kt
  experimentation/src/main/java/com/automattic/android/experimentation/repository/AssignmentsRepository.kt
  experimentation/src/test/java/com/automattic/android/experimentation/ExPlatTest.kt
  experimentation/src/test/java/com/automattic/android/experimentation/local/FileBasedCacheTest.kt
  experimentation/src/test/java/com/automattic/android/experimentation/remote/ExperimentRestClientTest.kt
Labels: enhancement
